### ISSUE TITLE
Searched app doesn't open

### ISSUE THREAD

**Issue by GunBrave** [twodayslate/Searchlight#7]
1. Open any app
2. Invoke Searchlight using Activator
3. Search for an app and click on searched app
4. Searched app opens for a split second and then dismisses itself or crashes phone into Safe Mode

The only tweaks installed on a newly restored (via Cydia Impactor) and jailbroken iPhone 6/8.4: Activator, Searchlight, PreferenceLoader, and associated files.

**Comment by GunBrave** [comment]
Crash log: https://ghostbin.com/paste/7nsxp
Syslog: https://ghostbin.com/paste/ursz9

**Comment by twodayslate** [comment]
What version of Searchlight are you experiencing this on?

**Comment by GunBrave** [comment]
1.04-226+debug

**Comment by GunBrave** [comment]
1.04-226+debug

**Comment by twodayslate** [comment]
Crash is related to issue https://github.com/twodayslate/Searchlight/issues/5. I would need a syslog of what is happening for the app not opening.

**Comment by GunBrave** [comment]
https://ghostbin.com/paste/7w7y9

**Comment by twodayslate** [comment]
Uploaded 1.04-229+debug

**Comment by GunBrave** [comment]
Yes it works!

There are still some quirks though. That strange split second animation still plays but the app pops up immediately afterwards. Also, it disables the first home button press after the app is launched.
